Fixed(MicRecorderAPI): Catch all exceptions when starting recording instead of just `IllegalStateException` and `IOException`
```
java.lang.RuntimeException: Unable to start service com.termux.api.apis.MicRecorderAPI$MicRecorderService@7c907ae with Intent { act=record cmp=com.termux.api/.apis.MicRecorderAPI$MicRecorderService (has extras) }: java.lang.RuntimeException: start failed.
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4338)
    at android.app.ActivityThread.access$1800(ActivityThread.java:237)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7664)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    Caused by: java.lang.RuntimeException: start failed.
    at android.media.MediaRecorder.start(Native Method)
    at com.termux.api.apis.MicRecorderAPI$MicRecorderService$2.handle(SourceFile:280)
    at com.termux.api.apis.MicRecorderAPI$MicRecorderService.onStartCommand(SourceFile:79)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4320)
```